#!/bin/sh

aws $* ec2 describe-instances --query="Reservations[].Instances[].{InstanceId:InstanceId, ImageId:ImageId, PrivateIpAddress:PrivateIpAddress, PublicIpAddress:PublicIpAddress, State:State.Name, Name:(Tags[?Key=='Name'].Value | [0])}"
